<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fir</string>
	</array>
	<key>name</key>
	<string>FIRRTL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;.*$\n?</string>
					<key>name</key>
					<string>comment.line.comma.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@\[.+\]</string>
					<key>name</key>
					<string>comment.line.fileinfo.firrtl</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
						<key>match</key>
						<string>\b(\d[\d_]*)\b</string>
						<key>name</key>
						<string>constant.numeric.decimal.firrtl</string>
				</dict>
				<dict>
						<key>match</key>
						<string>"h([\-]?[0-9a-fA-F]*)"</string>
						<key>name</key>
						<string>constant.numeric.hex.firrtl</string>
				</dict>
				<dict>
						<key>match</key>
						<string>"o([\-]?[0-7]*)"</string>
						<key>name</key>
						<string>constant.numeric.octal.firrtl</string>
				</dict>
				<dict>
						<key>match</key>
						<string>"b([\-]?[01]*)"</string>
						<key>name</key>
						<string>constant.numeric.bit.firrtl</string>
				</dict>
				<dict>
						<key>match</key>
						<string>\b(\-\d+)\b</string>
						<key>name</key>
						<string>constant.numeric.signed.firrtl</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*\b(add|sub|mul|eq|neq|geq|dshl|dshr|shl|not|and|or|neg|cvt|asUInt|asSInt|asClock|pad|cat|bits|mux|validif)\b(?=\()</string>
					<key>name</key>
					<string>support.function.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*\b(div|rem|gt|leq|lt|shr|xor|andr|orr|xorr|head|tail)\b(?=\()</string>
					<key>name</key>
					<string>support.function.firrtl</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=(node ))[A-Za-z0-9_]+|(?&lt;=(module ))[A-Za-z0-9_]+|(?&lt;=(reg ))[A-Za-z0-9_]+|(?&lt;=(wire ))[A-Za-z0-9_]+|(?&lt;=inst )[A-Za-z0-9_]+</string>
					<key>name</key>
					<string>variable.other.identifier.firrtl</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*\b(skip|wire|infer|read|write|rdwr|mport|output|input|cmem|smem|when|else|node|flip)\b</string>
					<key>name</key>
					<string>keyword.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\W*inst</string>
					<key>name</key>
					<string>keyword.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*\b(reg|((with)(?=\W*:\W*\()))|((reset)(?=\W*=>\W*))\b</string>
					<key>name</key>
					<string>keyword.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(([SU]Int.\d+>)|[SU]Int.\d+>\[\d+\]|[SU]Int|[SU]Int\[\d+\]|[SU]Int\[\d+\]\[\d+\]|[SU]Int.\d+>\[\d+\]\[\d+\]|Clock|module|circuit|extmodule)</string>
					<key>name</key>
					<string>support.class.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>invalid</string>
					<key>name</key>
					<string>invalid.firrtl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(&lt;=|&lt;\-)</string>
					<key>name</key>
					<string>keyword.operator.math.firrtl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(:|{|})</string>
					<key>name</key>
					<string>entity.name.firrtl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.firrtl</string>
	<key>uuid</key>
	<string>798F4D06-BAE8-40A8-8AA4-3307ABC03B34</string>
</dict>
</plist>
